# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       xorg-x11-drv-mtev

# >> macros
# << macros

Summary:    Multitouch input driver for Xserver
Version:    0.1.13
Release:    1
Group:      System/X Hardware Support
License:    GPLv2
URL:        http://gitorious.org/xorg/xf86-input-mtev
Source0:    %{name}-%{version}.tar.gz
Source100:  xorg-x11-drv-mtev.yaml
Patch0:     apis-match-for-xserver-1.10.1.patch
Patch1:     swapminmax.patch
Patch2:     rotation.patch
BuildRequires:  pkgconfig(xorg-server)
BuildRequires:  pkgconfig(xkbfile)
BuildRequires:  pkgconfig(xproto)
BuildRequires:  pkgconfig(inputproto)
BuildRequires:  pkgconfig(xrandr)
BuildRequires:  pkgconfig(randrproto)
BuildRequires:  pkgconfig(xextproto)
BuildRequires:  pkgconfig(mtdev)

%description
This is a xserver-xorg input driver for devices supporting Linux Multi-Touch protocol



%prep
%setup -q -n %{name}-%{version}

# apis-match-for-xserver-1.10.1.patch
%patch0 -p1
# swapminmax.patch
%patch1 -p1
# rotation.patch
%patch2 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
# >> files
%(pkg-config xorg-server --variable=moduledir )/input/mtev.so
# << files
